This notebook shows how the data is unified before unification. 

Please compare the resulting dataframes with those from the ingestion of the raw data (some data fields from the raw data may not be used in the harmonization).

In [1]:
import sys
import os

parent_dir = os.path.abspath("../")
sys.path.append(parent_dir)

import polars as pl
from chronoindex.dataset_loader import load_datasets

In [2]:
from chronoindex.dataset_harmonization import harmonize_loaded_aleppo, harmonize_loaded_colas, harmonize_loaded_zhao, harmonize_loaded_praes

In [3]:
datasets, errors = load_datasets(
    config_path= "datasets.toml",
    only=["aleppo","colas","zhao"],
)
if errors:
    raise RuntimeError(errors)

➡️ Loading datasets.aleppo
➡️ Loading datasets.colas
➡️ Loading datasets.zhao

## Aleppo, Colas, Zhao

In [4]:
aleppo = datasets["aleppo"]
colas= datasets["colas"]
zhao = datasets["zhao"]

In [5]:
# Harmonize them
hrm_aleppo = harmonize_loaded_aleppo(aleppo)
hrm_colas= harmonize_loaded_colas(colas)
hrm_zhao= harmonize_loaded_zhao(zhao)

👉 Data Harmonization: The Aleppo dataset provides timestamps only as days relative to enrollment. Absolute calendar dates are not available due to de-identification. During harmonization, a placeholder reference date (1990-01-01) is used as the enrollment date to reconstruct pseudo-datetimes.

### Let's inspect the main blocks.

**CGMData**

In [6]:
hrm_aleppo.CGMData.head()

shape: (5, 3)
┌─────┬─────────────────────────┬─────────────────────────────────┐
│ Id  ┆ CGM                     ┆ CGMTime                         │
│ --- ┆ ---                     ┆ ---                             │
│ str ┆ list[f64]               ┆ list[datetime[μs]]              │
╞═════╪═════════════════════════╪═════════════════════════════════╡
│ 263 ┆ [89.0, 87.0, … 159.0]   ┆ [1989-08-16 03:11:00, 1989-08-… │
│ 101 ┆ [97.0, 79.0, … 87.0]    ┆ [1989-10-28 15:23:56, 1989-10-… │
│ 105 ┆ [125.0, 125.0, … 124.0] ┆ [1990-02-21 18:59:55, 1990-02-… │
│ 109 ┆ [224.0, 160.0, … 107.0] ┆ [1990-01-01 19:15:48, 1990-01-… │
│ 240 ┆ [211.0, 55.0, … 175.0]  ┆ [1989-10-12 22:08:23, 1989-10-… │
└─────┴─────────────────────────┴─────────────────────────────────┘

In [7]:
hrm_colas.CGMData.head()

shape: (5, 3)
┌─────┬─────────────────────────┬─────────────────────────────────┐
│ Id  ┆ CGM                     ┆ CGMTime                         │
│ --- ┆ ---                     ┆ ---                             │
│ str ┆ list[f64]               ┆ list[datetime[μs]]              │
╞═════╪═════════════════════════╪═════════════════════════════════╡
│ 1   ┆ [86.0, 81.0, … 110.0]   ┆ [2012-01-01 00:00:14, 2012-01-… │
│ 2   ┆ [167.0, 163.0, … 133.0] ┆ [2012-01-01 00:00:35, 2012-01-… │
│ 3   ┆ [90.0, 90.0, … 97.0]    ┆ [2012-01-01 00:02:53, 2012-01-… │
│ 4   ┆ [93.0, 92.0, … 111.0]   ┆ [2012-01-01 00:01:42, 2012-01-… │
│ 5   ┆ [107.0, 109.0, … 134.0] ┆ [2012-01-01 00:01:39, 2012-01-… │
└─────┴─────────────────────────┴─────────────────────────────────┘

In [8]:
hrm_zhao.CGMData.head()

shape: (5, 3)
┌─────────────────┬─────────────────────────┬─────────────────────────────────┐
│ Id              ┆ CGM                     ┆ CGMTime                         │
│ ---             ┆ ---                     ┆ ---                             │
│ str             ┆ list[f64]               ┆ list[datetime[μs]]              │
╞═════════════════╪═════════════════════════╪═════════════════════════════════╡
│ 2000_0_20201230 ┆ [138.6, 120.6, … 88.2]  ┆ [2020-12-30 13:54:00, 2020-12-… │
│ 2001_0_20201102 ┆ [102.6, 97.2, … 136.8]  ┆ [2020-11-02 09:40:00, 2020-11-… │
│ 2001_1_20201117 ┆ [151.2, 145.8, … 180.0] ┆ [2020-11-17 09:19:00, 2020-11-… │
│ 2002_0_20210513 ┆ [257.4, 246.6, … 217.8] ┆ [2021-05-13 16:22:00, 2021-05-… │
│ 2003_0_20210615 ┆ [264.6, 262.8, … 180.0] ┆ [2021-06-15 17:20:00, 2021-06-… │
└─────────────────┴─────────────────────────┴─────────────────────────────────┘

**MetaData**

In [9]:
hrm_aleppo.MetaData.head()

shape: (5, 7)
┌─────┬─────┬─────┬────────┬────────┬───────────┬──────────────────┐
│ Id  ┆ Sex ┆ Age ┆ Height ┆ Weight ┆ BMI       ┆ Type of Diabetes │
│ --- ┆ --- ┆ --- ┆ ---    ┆ ---    ┆ ---       ┆ ---              │
│ str ┆ str ┆ i32 ┆ f64    ┆ f64    ┆ f64       ┆ str              │
╞═════╪═════╪═════╪════════╪════════╪═══════════╪══════════════════╡
│ 263 ┆ M   ┆ 44  ┆ 178.0  ┆ 106.0  ┆ 33.455376 ┆ T1DM             │
│ 101 ┆ M   ┆ 27  ┆ 183.0  ┆ 75.0   ┆ 22.395416 ┆ T1DM             │
│ 105 ┆ F   ┆ 42  ┆ 162.5  ┆ 62.0   ┆ 23.47929  ┆ T1DM             │
│ 109 ┆ F   ┆ 78  ┆ 163.0  ┆ 57.0   ┆ 21.453575 ┆ T1DM             │
│ 240 ┆ F   ┆ 68  ┆ 165.0  ┆ 63.0   ┆ 23.140497 ┆ T1DM             │
└─────┴─────┴─────┴────────┴────────┴───────────┴──────────────────┘

In [10]:
hrm_colas.MetaData.head()

shape: (5, 5)
┌─────┬─────┬─────┬───────────┬──────────────────┐
│ Id  ┆ Sex ┆ Age ┆ BMI       ┆ Type of Diabetes │
│ --- ┆ --- ┆ --- ┆ ---       ┆ ---              │
│ str ┆ str ┆ i32 ┆ f64       ┆ str              │
╞═════╪═════╪═════╪═══════════╪══════════════════╡
│ 1   ┆ F   ┆ 77  ┆ 25.4      ┆ Control          │
│ 2   ┆ M   ┆ 42  ┆ 30.0      ┆ Control          │
│ 3   ┆ M   ┆ 61  ┆ 33.799999 ┆ Control          │
│ 4   ┆ M   ┆ 67  ┆ 26.700001 ┆ Control          │
│ 5   ┆ F   ┆ 53  ┆ 25.799999 ┆ Control          │
└─────┴─────┴─────┴───────────┴──────────────────┘

In [11]:
hrm_zhao.MetaData.head()

shape: (5, 7)
┌─────────────────┬─────┬─────┬────────┬────────┬───────────┬──────────────────┐
│ Id              ┆ Sex ┆ Age ┆ Height ┆ Weight ┆ BMI       ┆ Type of Diabetes │
│ ---             ┆ --- ┆ --- ┆ ---    ┆ ---    ┆ ---       ┆ ---              │
│ str             ┆ str ┆ i32 ┆ f64    ┆ f64    ┆ f32       ┆ str              │
╞═════════════════╪═════╪═════╪════════╪════════╪═══════════╪══════════════════╡
│ 2000_0_20201230 ┆ M   ┆ 57  ┆ 1.69   ┆ 67.4   ┆ 23.6      ┆ T2DM             │
│ 2001_0_20201102 ┆ F   ┆ 69  ┆ 1.45   ┆ 55.8   ┆ 26.540001 ┆ T2DM             │
│ 2001_1_20201117 ┆ F   ┆ 69  ┆ 1.45   ┆ 53.2   ┆ 25.299999 ┆ T2DM             │
│ 2002_0_20210513 ┆ M   ┆ 57  ┆ 1.7    ┆ 70.0   ┆ 24.221453 ┆ T2DM             │
│ 2003_0_20210615 ┆ F   ┆ 58  ┆ 1.64   ┆ 62.5   ┆ 23.237656 ┆ T2DM             │
└─────────────────┴─────┴─────┴────────┴────────┴───────────┴──────────────────┘

**LabData**

In [12]:
hrm_aleppo.LabData.head()

shape: (5, 3)
┌─────┬─────────────────┬───────┐
│ Id  ┆ visit           ┆ HbA1c │
│ --- ┆ ---             ┆ ---   │
│ str ┆ str             ┆ f64   │
╞═════╪═════════════════╪═══════╡
│ 263 ┆ Screening Visit ┆ 7.0   │
│ 263 ┆ Randomization   ┆ 7.0   │
│ 263 ┆ Week 13 Visit   ┆ 6.7   │
│ 263 ┆ Week 26 Visit   ┆ 7.3   │
│ 101 ┆ Screening Visit ┆ 5.9   │
└─────┴─────────────────┴───────┘

In [13]:
hrm_colas.LabData.head()

shape: (5, 2)
┌─────┬───────┐
│ Id  ┆ HbA1c │
│ --- ┆ ---   │
│ str ┆ f64   │
╞═════╪═══════╡
│ 1   ┆ 6.3   │
│ 2   ┆ 5.8   │
│ 3   ┆ 5.5   │
│ 4   ┆ 6.0   │
│ 5   ┆ 5.2   │
└─────┴───────┘

In [14]:
hrm_zhao.LabData.head()

shape: (5, 18)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Id        ┆ Fasting   ┆ 2-hour    ┆ Fasting   ┆ … ┆ Estimated ┆ Uric Acid ┆ Blood     ┆ Hypoglyc │
│ ---       ┆ Plasma    ┆ Postprand ┆ C-peptide ┆   ┆ Glomerula ┆ ---       ┆ Urea      ┆ emia     │
│ str       ┆ Glucose   ┆ ial       ┆ ---       ┆   ┆ r Filtrat ┆ f64       ┆ Nitrogen  ┆ ---      │
│           ┆ ---       ┆ Plasma    ┆ f64       ┆   ┆ io…       ┆           ┆ ---       ┆ bool     │
│           ┆ f64       ┆ Glu…      ┆           ┆   ┆ ---       ┆           ┆ f64       ┆          │
│           ┆           ┆ ---       ┆           ┆   ┆ f64       ┆           ┆           ┆          │
│           ┆           ┆ f64       ┆           ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2000_0_20 ┆ 82.44     ┆ 162.36    ┆ 0.27      ┆ … ┆ 68.0      ┆ 245.0     ┆ 4.9       ┆ true     │
│ 201230    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2001_0_20 ┆ 137.7     ┆ 277.74    ┆ 0.64      ┆ … ┆ 101.0     ┆ 337.0     ┆ 5.6       ┆ true     │
│ 201102    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2001_1_20 ┆ 138.42    ┆ 277.2     ┆ 0.31      ┆ … ┆ 103.0     ┆ 262.0     ┆ 3.7       ┆ false    │
│ 201117    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2002_0_20 ┆ 158.4     ┆ 442.98    ┆ 0.39      ┆ … ┆ 105.0     ┆ 475.6     ┆ 4.74      ┆ false    │
│ 210513    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2003_0_20 ┆ 194.4     ┆ 238.5     ┆ 0.44      ┆ … ┆ 166.0     ┆ 490.05    ┆ 5.54      ┆ false    │
│ 210615    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

**Visit Timepoints**

In [15]:
# The other 2 don't have timepoints
hrm_aleppo.VisitTimepoints.head()

shape: (5, 3)
┌─────┬─────────────────┬────────────────┐
│ Id  ┆ visit           ┆ VisitTimepoint │
│ --- ┆ ---             ┆ ---            │
│ str ┆ str             ┆ date           │
╞═════╪═════════════════╪════════════════╡
│ 10  ┆ Screening Visit ┆ 1990-01-01     │
│ 10  ┆ Randomization   ┆ 1990-01-31     │
│ 10  ┆ Week 13 Visit   ┆ 1990-04-30     │
│ 10  ┆ Week 26 Visit   ┆ 1990-08-05     │
│ 101 ┆ Screening Visit ┆ 1989-12-13     │
└─────┴─────────────────┴────────────────┘

**Food**

In [16]:
# Missing for the other 2 datasets
hrm_zhao.Food.head()

shape: (5, 3)
┌─────────────────┬──────────────────┬───────────────┐
│ Id              ┆ food             ┆ FoodTimepoint │
│ ---             ┆ ---              ┆ ---           │
│ str             ┆ str              ┆ date          │
╞═════════════════╪══════════════════╪═══════════════╡
│ 2000_0_20201230 ┆ Rice 150 g       ┆ 2020-12-30    │
│                 ┆ Vegetable 100 g  ┆               │
│                 ┆ Sli…             ┆               │
│ 2000_0_20201230 ┆ Apple 70 g       ┆ 2020-12-31    │
│ 2000_0_20201230 ┆ Rice 100 g       ┆ 2020-12-31    │
│                 ┆ Spinach 150 g    ┆               │
│                 ┆ Beef …           ┆               │
│ 2000_0_20201230 ┆ Fried rice 100 g ┆ 2020-12-31    │
│ 2000_0_20201230 ┆ Vegetable 150 g  ┆ 2021-01-01    │
│                 ┆ Rice 100 g       ┆               │
└─────────────────┴──────────────────┴───────────────┘

## PRAESIIDIUM

In [17]:
datasets, errors = load_datasets(
    config_path= "datasets.toml",
    only=["praes_unil","praes_mug"],
)
if errors:
    raise RuntimeError(errors)

praes_unil = datasets["praes_unil"]
praes_mug = datasets["praes_mug"]

➡️ Loading datasets.praes_unil
➡️ Loading datasets.praes_mug
Error validating item with id s25471121: 2 validation errors for PSubject
visit3Form
  Input should be a valid dictionary or instance of Visit3Form [type=model_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.12/v/model_type
visit3AnalysisForm
  Input should be a valid dictionary or instance of VisitAnalysisResultForm [type=model_type, input_value=None, input_type=NoneType]

In [18]:
hrm_unil = harmonize_loaded_praes(praes_unil)

In [19]:
hrm_unil.CGMData

shape: (77, 3)
┌─────────────┬─────────────────────────────────┬─────────────────────────────────┐
│ Id          ┆ CGMTime                         ┆ CGM                             │
│ ---         ┆ ---                             ┆ ---                             │
│ str         ┆ list[datetime[μs]]              ┆ list[f64]                       │
╞═════════════╪═════════════════════════════════╪═════════════════════════════════╡
│ s24529531   ┆ [2024-06-05 10:25:00, 2024-06-… ┆ [95.4954, 100.9008, … 95.4954]  │
│ s24516746   ┆ [2024-05-21 14:16:00, 2024-05-… ┆ [75.6756, 72.072, … 109.9098]   │
│ s243281021  ┆ [2024-04-05 10:29:00, 2024-04-… ┆ [100.9008, 99.099, … 84.6846]   │
│ s245161136  ┆ [2024-05-23 12:27:00, 2024-05-… ┆ [97.2972, 99.099, … 90.09]      │
│ s24417854   ┆ [2024-04-24 12:47:00, 2024-04-… ┆ [88.2882, 88.2882, … 86.4864]   │
│ …           ┆ …                               ┆ …                               │
│ s2512892    ┆ [2025-02-05 14:26:00, 2025-02-… ┆ [99.099, 102.7026, … 63.063]    │
│ s2511498    ┆ [2025-01-14 12:10:00, 2025-01-… ┆ [115.3152, 118.9188, … 113.513… │
│ s2412161129 ┆ [2024-12-17 22:13:00, 2024-12-… ┆ [93.6936, 93.6936, … 91.8918]   │
│ s241210850  ┆ [2024-12-11 11:03:00, 2024-12-… ┆ [100.9008, 100.9008, … 106.306… │
│ s251141250  ┆ [2025-01-22 00:59:00, 2025-01-… ┆ [93.6936, 93.6936, … 97.2972]   │
└─────────────┴─────────────────────────────────┴─────────────────────────────────┘

In [20]:
hrm_unil.MetaData

shape: (77, 6)
┌─────────────┬──────┬─────┬────────┬────────┬───────────┐
│ Id          ┆ Age  ┆ Sex ┆ Weight ┆ Height ┆ BMI       │
│ ---         ┆ ---  ┆ --- ┆ ---    ┆ ---    ┆ ---       │
│ str         ┆ f64  ┆ str ┆ f64    ┆ f64    ┆ f64       │
╞═════════════╪══════╪═════╪════════╪════════╪═══════════╡
│ s24529531   ┆ 55.0 ┆ F   ┆ 78.0   ┆ 166.5  ┆ 28.136244 │
│ s24516746   ┆ 26.9 ┆ F   ┆ 79.5   ┆ 171.0  ┆ 27.187853 │
│ s243281021  ┆ 40.0 ┆ F   ┆ 79.9   ┆ 163.2  ┆ 29.998979 │
│ s245161136  ┆ 29.0 ┆ F   ┆ 67.0   ┆ 160.0  ┆ 26.171875 │
│ s24417854   ┆ 37.0 ┆ M   ┆ 95.0   ┆ 174.0  ┆ 31.377989 │
│ …           ┆ …    ┆ …   ┆ …      ┆ …      ┆ …         │
│ s2512892    ┆ 50.0 ┆ M   ┆ 95.0   ┆ 174.0  ┆ 31.377989 │
│ s2511498    ┆ 33.0 ┆ M   ┆ 102.4  ┆ 185.0  ┆ 29.919649 │
│ s2412161129 ┆ 49.0 ┆ F   ┆ 69.8   ┆ 162.0  ┆ 26.596555 │
│ s241210850  ┆ 24.0 ┆ M   ┆ 96.2   ┆ 178.5  ┆ 30.192469 │
│ s251141250  ┆ 35.0 ┆ F   ┆ 67.0   ┆ 160.0  ┆ 26.171875 │
└─────────────┴──────┴─────┴────────┴────────┴───────────┘

In [21]:
hrm_unil.VisitTimepoints

shape: (231, 3)
┌────────────┬─────────┬────────────────┐
│ Id         ┆ visit   ┆ VisitTimepoint │
│ ---        ┆ ---     ┆ ---            │
│ str        ┆ str     ┆ date           │
╞════════════╪═════════╪════════════════╡
│ s241081147 ┆ visit 1 ┆ 2024-10-10     │
│ s241081147 ┆ visit 2 ┆ 2024-12-19     │
│ s241081147 ┆ visit 3 ┆ 2025-02-05     │
│ s241112738 ┆ visit 1 ┆ 2024-11-15     │
│ s241112738 ┆ visit 2 ┆ 2025-01-15     │
│ …          ┆ …       ┆ …              │
│ s25128853  ┆ visit 2 ┆ 2025-04-02     │
│ s25128853  ┆ visit 3 ┆ 2025-06-05     │
│ s2512892   ┆ visit 1 ┆ 2025-02-05     │
│ s2512892   ┆ visit 2 ┆ 2025-04-08     │
│ s2512892   ┆ visit 3 ┆ 2025-06-11     │
└────────────┴─────────┴────────────────┘

In [22]:
hrm_unil.LabData

shape: (231, 37)
┌────────────┬─────────┬───────┬───────────────────────┬───┬──────┬───────┬───────┬─────────┐
│ Id         ┆ visit   ┆ HbA1c ┆ Fasting_blood_glucose ┆ … ┆ IL_2 ┆ IL_6  ┆ IL_10 ┆ Leptin  │
│ ---        ┆ ---     ┆ ---   ┆ ---                   ┆   ┆ ---  ┆ ---   ┆ ---   ┆ ---     │
│ str        ┆ str     ┆ f64   ┆ f64                   ┆   ┆ f64  ┆ f64   ┆ f64   ┆ f64     │
╞════════════╪═════════╪═══════╪═══════════════════════╪═══╪══════╪═══════╪═══════╪═════════╡
│ s241081147 ┆ visit 1 ┆ null  ┆ 4.81                  ┆ … ┆ 0.29 ┆ 7.39  ┆ 19.21 ┆ 5000.6  │
│ s241081147 ┆ visit 2 ┆ 5.27  ┆ 4.55                  ┆ … ┆ 0.28 ┆ 5.73  ┆ 0.0   ┆ 11147.6 │
│ s241081147 ┆ visit 3 ┆ 5.69  ┆ 4.98                  ┆ … ┆ 0.32 ┆ 14.59 ┆ 1.94  ┆ 6956.3  │
│ s241112738 ┆ visit 1 ┆ null  ┆ 5.19                  ┆ … ┆ 0.23 ┆ 4.1   ┆ 0.0   ┆ 5648.1  │
│ s241112738 ┆ visit 2 ┆ 5.55  ┆ 5.26                  ┆ … ┆ 0.27 ┆ 5.6   ┆ 0.01  ┆ 6517.1  │
│ …          ┆ …       ┆ …     ┆ …                     ┆ … ┆ …    ┆ …     ┆ …     ┆ …       │
│ s25128853  ┆ visit 2 ┆ 4.97  ┆ 5.22                  ┆ … ┆ 0.31 ┆ 0.2   ┆ 82.38 ┆ 12875.5 │
│ s25128853  ┆ visit 3 ┆ 4.85  ┆ 5.27                  ┆ … ┆ 0.14 ┆ 2.5   ┆ 76.71 ┆ 12076.9 │
│ s2512892   ┆ visit 1 ┆ null  ┆ 4.99                  ┆ … ┆ 0.41 ┆ 1.8   ┆ 0.0   ┆ 0.0     │
│ s2512892   ┆ visit 2 ┆ 5.24  ┆ 5.03                  ┆ … ┆ 0.53 ┆ 0.2   ┆ 0.0   ┆ 3111.3  │
│ s2512892   ┆ visit 3 ┆ 5.02  ┆ 4.73                  ┆ … ┆ 0.41 ┆ 0.2   ┆ 0.98  ┆ 2914.7  │
└────────────┴─────────┴───────┴───────────────────────┴───┴──────┴───────┴───────┴─────────┘

In [23]:
hrm_unil.Food

shape: (8_287, 8)
┌────────────┬───────────────┬───────────┬───────────────┬──────────┬─────────┬──────────┬─────────┐
│ Id         ┆ FoodTimepoint ┆ meal      ┆ food          ┆ calories ┆ carbs   ┆ proteins ┆ fats    │
│ ---        ┆ ---           ┆ ---       ┆ ---           ┆ ---      ┆ ---     ┆ ---      ┆ ---     │
│ str        ┆ datetime[μs]  ┆ str       ┆ str           ┆ f64      ┆ f64     ┆ f64      ┆ f64     │
╞════════════╪═══════════════╪═══════════╪═══════════════╪══════════╪═════════╪══════════╪═════════╡
│ s241081147 ┆ 2024-10-10    ┆ Breakfast ┆ ŪDENS, KRĀNA  ┆ 634.9095 ┆ 22.411  ┆ 19.3885  ┆ 48.429  │
│            ┆ 08:00:00      ┆           ┆ ŪDENS (200    ┆          ┆         ┆          ┆         │
│            ┆               ┆           ┆ ml). O…       ┆          ┆         ┆          ┆         │
│ s241081147 ┆ 2024-10-10    ┆ Lunch     ┆ CŪKGAĻAS      ┆ 766.652  ┆ 5.48    ┆ 79.64    ┆ 45.336  │
│            ┆ 12:30:00      ┆           ┆ KARBONĀDE,    ┆          ┆         ┆          ┆         │
│            ┆               ┆           ┆ KOTLETES (…   ┆          ┆         ┆          ┆         │
│ s241081147 ┆ 2024-10-10    ┆ Dinner    ┆ LAPU SALĀTI   ┆ 1095.826 ┆ 66.8985 ┆ 42.2055  ┆ 71.789  │
│            ┆ 15:30:00      ┆           ┆ (100 g).      ┆          ┆         ┆          ┆         │
│            ┆               ┆           ┆ LASIS, KĀ…    ┆          ┆         ┆          ┆         │
│ s241081147 ┆ 2024-10-11    ┆ Breakfast ┆ ŪDENS, KRĀNA  ┆ 0.0      ┆ 0.0     ┆ 0.0      ┆ 0.0     │
│            ┆ 03:20:20.824  ┆           ┆ ŪDENS (100    ┆          ┆         ┆          ┆         │
│            ┆               ┆           ┆ ml)           ┆          ┆         ┆          ┆         │
│ s241081147 ┆ 2024-10-11    ┆ Breakfast ┆ TOMĀTI (250   ┆ 56.825   ┆ 8.625   ┆ 1.375    ┆ 0.75    │
│            ┆ 06:44:26.451  ┆           ┆ g)            ┆          ┆         ┆          ┆         │
│ …          ┆ …             ┆ …         ┆ …             ┆ …        ┆ …       ┆ …        ┆ …       │
│ s2512892   ┆ 2025-06-09    ┆ Dinner    ┆ KAFIJA (250   ┆ 525.516  ┆ 49.2285 ┆ 10.275   ┆ 31.7685 │
│            ┆ 13:30:00      ┆           ┆ ml). SIERA    ┆          ┆         ┆          ┆         │
│            ┆               ┆           ┆ PĪRĀDZI…      ┆          ┆         ┆          ┆         │
│ s2512892   ┆ 2025-06-11    ┆ Breakfast ┆ SIERS,        ┆ 533.1315 ┆ 1.819   ┆ 17.4145  ┆ 49.6705 │
│            ┆ 03:45:10.459  ┆           ┆ MOCARELLAS    ┆          ┆         ┆          ┆         │
│            ┆               ┆           ┆ SIERS, 20% T… ┆          ┆         ┆          ┆         │
│ s2512892   ┆ 2025-06-11    ┆ Lunch     ┆ ZIRŅU ZUPA AR ┆ 767.82   ┆ 49.2175 ┆ 50.645   ┆ 34.6    │
│            ┆ 10:30:10.459  ┆           ┆ CŪKGAĻU (250  ┆          ┆         ┆          ┆         │
│            ┆               ┆           ┆ g).…          ┆          ┆         ┆          ┆         │
│ s2512892   ┆ 2025-06-11    ┆ Afternoon ┆ KAFIJA (250   ┆ 7.975    ┆ 0.75    ┆ 0.775    ┆ 0.2     │
│            ┆ 13:00:10.459  ┆           ┆ ml)           ┆          ┆         ┆          ┆         │
│ s2512892   ┆ 2025-06-11    ┆ Dinner    ┆ BIEZPIENA     ┆ 278.574  ┆ 37.149  ┆ 6.385    ┆ 10.641  │
│            ┆ 17:30:10.459  ┆           ┆ SIERIŅŠ,      ┆          ┆         ┆          ┆         │
│            ┆               ┆           ┆ KĀRUMS, VAN…  ┆          ┆         ┆          ┆         │
└────────────┴───────────────┴───────────┴───────────────┴──────────┴─────────┴──────────┴─────────┘

In [24]:
hrm_unil.PhysicalActivity

shape: (8_410, 7)
┌────────────┬───────────────┬───────┬──────────┬────────────┬───────────┬──────────┐
│ Id         ┆ activity_name ┆ steps ┆ calories ┆ startDate  ┆ startTime ┆ duration │
│ ---        ┆ ---           ┆ ---   ┆ ---      ┆ ---        ┆ ---       ┆ ---      │
│ str        ┆ str           ┆ i64   ┆ i64      ┆ str        ┆ str       ┆ i64      │
╞════════════╪═══════════════╪═══════╪══════════╪════════════╪═══════════╪══════════╡
│ s241081147 ┆ Walk          ┆ 2718  ┆ 162      ┆ 2024-10-10 ┆ 16:20     ┆ 2099000  │
│ s241081147 ┆ Walk          ┆ 1477  ┆ 83       ┆ 2024-10-10 ┆ 19:16     ┆ 1075000  │
│ s241081147 ┆ Walk          ┆ 1680  ┆ 97       ┆ 2024-10-10 ┆ 20:08     ┆ 1331000  │
│ s241081147 ┆ Walk          ┆ 2245  ┆ 121      ┆ 2024-10-11 ┆ 06:48     ┆ 1485000  │
│ s241081147 ┆ Walk          ┆ 2766  ┆ 178      ┆ 2024-10-11 ┆ 16:50     ┆ 2713000  │
│ …          ┆ …             ┆ …     ┆ …        ┆ …          ┆ …         ┆ …        │
│ s2512892   ┆ Run           ┆ 9566  ┆ 1044     ┆ 2025-06-05 ┆ 19:31     ┆ 3549000  │
│ s2512892   ┆ Walk          ┆ 7669  ┆ 799      ┆ 2025-06-07 ┆ 15:48     ┆ 6450000  │
│ s2512892   ┆ Run           ┆ 9539  ┆ 989      ┆ 2025-06-08 ┆ 10:00     ┆ 3518000  │
│ s2512892   ┆ Walk          ┆ 1877  ┆ 210      ┆ 2025-06-09 ┆ 13:54     ┆ 1894000  │
│ s2512892   ┆ Run           ┆ 7452  ┆ 654      ┆ 2025-06-10 ┆ 19:07     ┆ 2938000  │
└────────────┴───────────────┴───────┴──────────┴────────────┴───────────┴──────────┘